!function(){var f,l=this&&this.I||function(a,b){function c(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)};function m(){}m.prototype.onUnavailable=function(){};function p(a){var b=Array.prototype,c=b.toJSON;return c?(delete b.toJSON,a=JSON.stringify(a),b.toJSON=c,a):JSON.stringify(a)}
function q(){this.crossPriority=0;this.largePriority=10;this.syncPriority=100;this.storeType=4;try{if(this.a=self.localStorage)this.a.setItem("ct.ls.k","ct.ls.v"),"ct.ls.v"===this.a["ct.ls.k"]&&(this.isAvailable=!0),this.a.removeItem("ct.ls.k")}catch(a){r(this)}}l(q,m);q.prototype.add=function(a,b){a.locator.key="ct.ls."+a.locator.key;this.update(a,b);return a.locator};q.prototype.remove=function(a,b){var c=this;t(this,function(){return c.a.removeItem(a.key)},function(){return b(a)})};
q.prototype.update=function(a,b){var c=this;t(this,function(){return c.a.setItem(a.locator.key,p(a.c))},function(){return b(a.locator)})};q.prototype.getAll=function(a){var b=this,c=[];t(this,function(){u(b,function(a){c.push({c:JSON.parse(b.a[a]),locator:{key:a,storeType:b.storeType}})});a(c)},function(){return a(c)})};function t(a,b,c){try{b()}catch(d){r(a),setTimeout(function(){return c},0)}}function r(a){a.isAvailable=!1;a.onUnavailable();u(a,function(b){return a.a.removeItem(b)})}
function u(a,b){if(a.a)for(var c in a.a)0===c.indexOf("ct.ls.")&&b(c)}
function v(){var a=this;this.f=[];this.crossPriority=this.syncPriority=0;this.isAvailable=!0;this.largePriority=100;this.storeType=3;try{if(self.indexedDB){var b=function(){return w(a)},c=indexedDB.open("ct.db",2);c.onupgradeneeded=function(b){if(b=x(a,b.target))b.objectStoreNames.contains("ct.db.os")&&b.deleteObjectStore("ct.db.os"),b.objectStoreNames.contains("ct.db.st")||b.createObjectStore("ct.db.st").createIndex("sid","sid",{unique:!1})};c.onsuccess=function(c){var e=a.a;!e&&(e=x(a,c.target))&&
(e.onabort=e.onversionchange=e.onclose=b,a.b=!0,y(a))};c.onerror=c.onblocked=b}}catch(d){w(this)}}l(v,m);function x(a,b){if(b.result.constructor===IDBDatabase)return b.result;w(a);return null}v.prototype.add=function(a,b){a.locator.key="ct.db."+a.locator.key;this.update(a,b);return a.locator};v.prototype.remove=function(a,b){A(this,this.remove,1,[a.key],a,b)};v.prototype.update=function(a,b){A(this,this.update,0,[a.c,a.locator.key],a,b)};
v.prototype.getAll=function(a){var b=this,c=[];if(this.b)try{var d=this.a.transaction("ct.db.st","readonly");d.onabort=d.onerror=d.oncomplete=function(){return a(c)};d.objectStore("ct.db.st").openCursor().onsuccess=function(a){(a=a.target.result)&&a.constructor===IDBCursorWithValue&&(c.push({c:a.value,locator:{key:a.key,storeType:b.storeType}}),a["continue"]())}}catch(e){e.constructor===DOMException&&"InvalidStateError"===e.name&&(this.a.objectStoreNames.contains("ct.db.st")||w(this)),a(c)}else C(this,
this.getAll,[a])};function y(a){var b=setTimeout(function(){clearTimeout(b);var c=a.f.shift();c&&(c.w.apply(a,c.D),y(a))},0)}function w(a){a.isAvailable=a.b=!1;try{a.a.close()}catch(b){}a.a=null;a.onUnavailable()}
function A(a,b,c,d,e,z){var k=e.locator||e;if(!a.b||a.g)C(a,b,[e,z]);else try{a.g=!0;var g=a.a.transaction("ct.db.st","readwrite");g.onabort=g.onerror=function(){D(a);z(k)};g.oncomplete=function(){return D(a)};var n=g.objectStore("ct.db.st");switch(c){case 0:n.put(d[0],d[1]);break;case 1:n["delete"](d[0])}}catch(h){w(a),D(a),z(k)}}function D(a){a.g=!1;y(a)}function C(a,b,c){a.f.push({w:b,D:c})}function E(a,b,c){this.a=a;this.f=b;this.b=c;this.a.registerDispatcher(b)}f=E.prototype;f.throttleUp=function(){this.a.throttleUp()};
f.deThrottle=function(){this.a.deThrottle()};f.stopSession=function(a,b){this.a.stopSession(a,b||this.b)};f.startSession=function(a,b){this.a.startSession(a,b||this.b)};f.extendSession=function(a,b){this.a.extendSession(a,b||this.b)};f.sendMessages=function(){this.f.dispatched||(this.f.dispatched=!0,this.a.sendMessages())};f.removeMessage=function(a){this.a.removeMessage(a)};f.storeMessage=function(a,b,c,d){return this.a.storeMessage(a,b,c,d)};
function F(a,b){var c=this;this.j=a;this.m=b;this.h=this.l=0;this.b=[];this.i=[];this.g={};this.a={};this.f={};this.o=[];this.s();this.h=b.curr();a.forEach(function(a){return a.onUnavailable=c.s.bind(c)})}f=F.prototype;f.registerDispatcher=function(a){var b=this;a.supportedMessageNames.forEach(function(c){return b.g[c]=a})};f.unregisterDispatcher=function(a){var b=this;a.supportedMessageNames.forEach(function(a){return delete b.g[a]})};f.throttleUp=function(){this.h=this.m.next()};
f.deThrottle=function(){this.m.reset();this.h=this.m.curr()};f.stopSession=function(a,b){this.a[a]&&(this.extendSession(a,b),delete this.a[a])};f.startSession=function(a,b){var c=this,d=Date.now();if(!this.a[a]){var e=void 0;this.a[a]=e=G({sid:a,created:d,expires:d+b},1);H(this,e,function(){return delete c.a[a]},!1,!1)}};f.extendSession=function(a,b){var c;if(c=this.a[a]){c.c.item.expires=Date.now()+b;var d=J(this,c.locator);this.a[a]=c;d&&d.update(c,function(){})}};
f.storeMessage=function(a,b,c,d){return this.a[a.sid]?(a=G(a,2),H(this,a,function(a){return b(a)},c,d),a.locator):null};f.removeMessage=function(a){K(this,{u:a,F:0})};
f.sendMessages=function(){var a=this,b=0,c=[],d=this.j.filter(function(a){return a.isAvailable});this.i.forEach(function(b){a.g[b.c.item.name]&&a.b.push(b)});d.forEach(function(e){return e.getAll(function(e){c=c.concat(e);if(++b===d.length){e=c;for(var k,g=null,n=0;n<e.length;n++){var h=e[n];if(k=h.c.item){var B=h.c.type;1!==B||a.a[k.sid]||a.f[k.sid]?2===B&&-1===a.b.indexOf(h)&&-1===a.i.indexOf(h)&&a.b.push(h):(g&&g.c.type===B&&(g.c.item.expires=0),a.f[k.sid]=h,a.b.push(h))}g=h}L(a)}})})};
function G(a,b){return{c:{v:1,type:b,item:a},locator:{storeType:0,key:Date.now()+"."+parseInt(1E6*(Math.random()+1),10)}}}function H(a,b,c,d,e){(a=d&&a.C||e&&a.G||a.H)?(b.locator.storeType=a.storeType,a.add(b,c)):c(b.locator)}function K(a,b){function c(){3>++b.F&&a.o.push(b);M(a.B.bind(a),1E3)}var d=b.u,e=J(a,b.u);e?e.remove(d,c):c()}function L(a){a.l=M(a.A.bind(a),a.h,function(){return a.l=0})}function M(a,b,c){var d=setTimeout(function(){c&&c();clearTimeout(d);a()},b);return d}
f.A=function(){var a=this,b=this.b.shift();if(b){var c=b.c.item,d=this.g[c.name];(c=(c=this.f[c.sid])&&c.c.item)?c.expires<Date.now()?(delete this.f[c.sid],this.removeMessage(b.locator)):d&&d.isAvailable?d.dispatch({message:b.c.item,locator:b.locator},{defer:function(){a.b.push(b);a.l||L(a)},reject:function(){a.removeMessage(b.locator)},resolve:function(){a.i.push(b)}}):this.i.push(b):this.removeMessage(b.locator);L(this)}};f.B=function(){var a=this.o.shift();a&&K(this,a)};
function J(a,b){return a.j.filter(function(a){return a.storeType===b.storeType&&a.isAvailable})[0]}f.s=function(){var a=this.j.filter(function(a){return a.isAvailable});this.H=a.filter(function(a){return 0<a.syncPriority}).sort(function(a,c){return c.syncPriority-a.syncPriority})[0];this.G=a.filter(function(a){return 0<a.largePriority}).sort(function(a,c){return c.largePriority-a.largePriority})[0];this.C=a.filter(function(a){return 0<a.crossPriority}).sort(function(a,c){return c.crossPriority-a.crossPriority})[0]};
function N(a,b){void 0===a&&(a=3E4);void 0===b&&(b=window);this.g=a;this.f=-1;this.b=b;this.syncPriority=10;this.largePriority=this.crossPriority=0;this.storeType=2;if(0===this.b.name.length)this.a={},O(this),this.isAvailable=!0;else if("_CT_"===this.b.name.substr(0,4))try{this.a=JSON.parse(this.b.name.substr(4,this.b.name.length));this.isAvailable=!0;var c=Object.keys(this.a);0<c.length&&(this.f=parseInt(c[c.length-1],10))}catch(d){P(this)}else P(this)}l(N,m);
function O(a){a.b.name="_CT_"+p(a.a)}function P(a){a.isAvailable=!1;a.onUnavailable()}function Q(a){if("_CT_"===a.b.name.substr(0,4))return!1;P(a);return!0}N.prototype.add=function(a){if(Q(this))return null;if(this.b.name.length>this.g)return P(this),null;a.locator.key=(++this.f).toString();this.a[this.f]=a.c;O(this);return a.locator};N.prototype.remove=function(a){Q(this)||(delete this.a[a.key],O(this))};N.prototype.update=function(a){Q(this)||(this.a[a.locator.key]=a.c,O(this))};
N.prototype.getAll=function(a){var b=[];if(!Q(this))for(var c in this.a)b.push({c:this.a[c],locator:{key:c,storeType:this.storeType}});a(b)};var R="object"===typeof module&&"object"===typeof module.exports,S=(R?module.exports.ClickTaleGlobal:self.ClickTaleGlobal)||{};S.persistence={IndexedDbProvider:v,PersistenceClient:E,PersistenceManager:F,LocalStorageProvider:q,WindowNameProvider:N,PersistenceDispatcher:function(a){this.supportedMessageNames=a}};R?module.exports=S:self.ClickTaleGlobal=S;ClickTaleGlobal.persistence.version="0.1.31";}.call({});
!function(){var h,k=this&&this.ab||function(a,b){function c(){this.constructor=a}for(var d in b)b.hasOwnProperty(d)&&(a[d]=b[d]);a.prototype=null===b?Object.create(b):(c.prototype=b.prototype,new c)},m={end:0,f:1,a:2,c:3,b:4,0:"end",1:"init",2:"chunk",3:"preinit",4:"exclude"};function n(){}n.prototype.a=function(a){return this.f.a(a)};n.prototype.b=function(a){this.f=a};function p(){}k(p,n);
p.prototype.a=function(a){var b=a.cmpn,c=self.URLSearchParams,c=c?c.prototype.get.bind(new c(location.search)):this.c;return(c=aa(c)())&&c!==b?(a.cmpn=c,!0):this.g.a(a)};function aa(a){return function(){return decodeURIComponent(a("utm_campaign")||"")}}p.prototype.c=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");return(a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(self.location.search))?decodeURIComponent(a[1].replace(/\+/g," ")):""};p.prototype.b=function(a){this.g=a};
var ba={visitId:3,version:6,screenX:16,screenY:17,browser:18,location:7,projectId:1,visitorId:2,messageId:5,eventIds:21,rotation:27,pageTags:35,pageviewId:4,viewportX:29,viewportY:30,timeOnPage:12,adobeMCVID:33,gaClientId:34,numOfClicks:14,scrollReach:13,appLoadTime:98,interactions:28,jsErrorCount:11,goalOriented:24,engagementTime:9,firstPageview:31,adobeLegacyId:32,discardedTags:36,browserVersion:19,lackOfInterest:23,attentionSplit:26,timeToProcess:100,briefMovement:101,documentReferrer:8,clientTimeStamp:22,
navigationStart:99,domContentLoaded:10,carelessScrolling:25,durationSinceLastVisit:15,abTest:60,cartValue:61,cartUpdate:62,action:63,campaign:64,error:65,3:"visitId",6:"version",16:"screenX",17:"screenY",18:"browser",7:"location",1:"projectId",2:"visitorId",5:"messageId",21:"eventIds",27:"rotation",35:"pageTags",4:"pageviewId",29:"viewportX",30:"viewportY",12:"timeOnPage",33:"adobeMCVID",34:"gaClientId",14:"numOfClicks",13:"scrollReach",98:"appLoadTime",28:"interactions",11:"jsErrorCount",24:"goalOriented",
9:"engagementTime",31:"firstPageview",32:"adobeLegacyId",36:"discardedTags",19:"browserVersion",23:"lackOfInterest",26:"attentionSplit",100:"timeToProcess",101:"briefMovement",8:"documentReferrer",22:"clientTimeStamp",99:"navigationStart",10:"domContentLoaded",25:"carelessScrolling",15:"durationSinceLastVisit",60:"abTest",61:"cartValue",62:"cartUpdate",63:"action",64:"campaign",65:"error"},q={error:0,keyup:1,scroll:2,resize:3,unload:4,submit:5,online:6,mouseup:7,offline:8,mousedown:9,mouseover:10,
touchstart:11,beforeunload:12,DOMContentLoaded:13,visibilitychange:14,0:"error",1:"keyup",2:"scroll",3:"resize",4:"unload",5:"submit",6:"online",7:"mouseup",8:"offline",9:"mousedown",10:"mouseover",11:"touchstart",12:"beforeunload",13:"DOMContentLoaded",14:"visibilitychange"};function r(a,b,c,d){void 0===a&&(a=!1);void 0===b&&(b=!0);void 0===c&&(c=!0);void 0===d&&(d=!1);this.f=a;this.J=b;this.w=c;this.o=d;this.Y=this.ca=!1;this.sa=null}
r.prototype.l=function(a){a=this.h(a);this.Y=!this.ca&&a!==this.sa&&null!==a;this.sa=a;return{type:this.a,value:a}};function t(a,b,c,d){void 0===b&&(b=!1);void 0===c&&(c=!0);void 0===d&&(d=!0);r.call(this,b,c,d,!!(a&&a.metrics&&a.metrics.enableOptionalEndMetrics));this.f=b;this.J=c;this.w=d}k(t,r);function v(a,b){t.call(this,b);this.b=a;this.c=0;this.a=14;this.b.bind([7],this.m.bind(this));this.b.bind([9],this.g.bind(this))}k(v,t);v.prototype.g=function(a){this.i=a.target};
v.prototype.m=function(a){this.i===a.target&&this.c++};v.prototype.h=function(){return this.c};function w(){r.call(this,!1,!0,!1)}k(w,r);function ca(a){w.call(this);this.timing=a;this.a=99}k(ca,w);ca.prototype.h=function(){return this.timing.navigationStart};var x="undefined"!==typeof ClickTaleGlobal&&ClickTaleGlobal.logger?ClickTaleGlobal.logger.createLogger(2):{close:function(){},addToContext:function(){},debug:function(){},info:function(){},warn:function(){},error:function(){},jsError:function(){}};
function y(){return(new Date).getTime()}function da(a){return a.match(/[a-z]+/gi).map(function(a){return a.charAt(0).toUpperCase()+a.substr(1).toLowerCase()}).join("")}function ea(a){var b=Array.prototype,c=b.toJSON;return c?(delete b.toJSON,a=JSON.stringify(a),b.toJSON=c,a):JSON.stringify(a)}function fa(a){var b=null;try{b=a()}catch(c){x.error("ex1",c)}return b}var ha=Math.pow(2,53)-1;
function z(a,b,c){r.call(this,c[0],c[1],c[2],c[3]);this.m=[];this.F=[];this.S={};this.i=!0;this.ea={type:function(a,b,c,g){(a=typeof b[c]===g)||x.error("de#1",{ja:"type",data:b},"dataEvents");return a},required:function(a,b,c){(a=b.hasOwnProperty(c))||x.error("de#2",{ja:"required",data:b},"dataEvents");return a},C:function(a,b,c,g){(a=void 0!==b[c]&&"string"===typeof b[c])?b[c]=b[c].slice(0,g):x.error("de#3",{ja:"limit",data:b},"dataEvents");return a},values:function(a,b,c,g){a=g.indexOf(b[c]);-1!==
a?b[c]=a:(b[c]=0,x.error("de#4",{ja:"values",data:b},"dataEvents"));return!0}};this.a=this.u();ia(b,this.da.bind(this))}k(z,r);z.prototype.h=function(a){var b=this.m.concat(this.F);if(a=b.length?this.g(b,0===a):null)this.F=this.F.concat(this.m.slice(0)),this.m=[];return a};z.prototype.da=function(){this.F.length=0};
z.prototype.add=function(a){var b=!0,c=this.b,d;for(d in c)if(c.hasOwnProperty(d)){var e;e=c[d];if(null!=e&&"object"==typeof e){var f=e.constructor(),g=void 0;for(g in e)e.hasOwnProperty(g)&&(f[g]=e[g]);e=f}f=e.required;e.hasOwnProperty("required")&&delete e.required;for(var l in e)if(e.hasOwnProperty(l)&&(b=this.ea[l](this,a,d,e[l]),!b))break;f||b||(b=!0,delete a[d]);if(!b)break}b&&(delete a.event,b=ja(a),(c=this.i&&void 0!==this.S[b])||(c=this.c,c=void 0===c?!1:Object.keys(this.S).length>=c),c||
(this.S[b]=a,this.m.push(a)))};function ja(a){return Object.keys(a).map(function(b){return a[b]}).join("|")}function A(a,b){z.call(this,0,b,[!1,!1,!0,!0]);this.c=Infinity;this.i=!1;this.b={type:{values:["other","error","message"],required:!0},message:{type:"string",C:50,required:!0},code:{type:"string",required:!1,C:10}}}k(A,z);A.prototype.g=function(a,b){return b?ka(a):a};
function ka(a){return a.reduce(function(a,c,d){return a+(""+(0!==d?"\v":"")+c.type+"\v"+c.message+"\v"+(c.code?c.code:""))},"")}A.prototype.u=function(){return 65};function la(a){for(var b=arguments.length,c,d,e,f,g,l=1;l<b;l++)if(c=arguments[l])for(d in c)e=a[d],f=c[d],a!==f&&(f&&(ma(f)||(g=Array.isArray(f)))?g?(g=!1,a[d]=f.slice()):(e=e&&ma(e)?e:{},a[d]=la(e,f)):void 0!==f&&(a[d]=f));return a}
function ma(a){return"object"!==(null==a?a+"":"object"===typeof a||"function"===typeof a?na[oa.call(a)]||"object":typeof a)||a.nodeType||a===window||a.constructor&&!pa.call(a.constructor.prototype,"isPrototypeOf")?!1:!0}var na={},oa=na.toString,pa=na.hasOwnProperty,B;function C(){return B||(B=qa(self.ClickTaleMonitor.Settings.config))}
function qa(a){return la(B||{metrics:{inactivityTime:2E4,interestInterval:12E3,maxFetchInterval:5E3,touchMouseIgnoreTime:500,goalOrientedCloseInterval:2E3,enableOptionalEndMetrics:!0,maxPageTagLength:50,pageTagRedundancy:3,maxPageTagsPerPage:10,maxTagsOnEnd:3,modifiedChunkToggle:!0,maxChunkInactivity:2,providers:"TagsMetric BrowserMetric EventIdsMetric TimeOnPageMetric ScrollReachMetric AppLoadTimeMetric InputMethodMetric JSErrorCountMetric GoalOrientedMetric DiscardedTagsMetric FirstPageviewMetric ViewPortWidthMetric AdobeLegacyIdMetric ViewPortHeightMetric NumberOfClicksMetric BrowserVersionMetric LackOfInterestMetric AttentionSplitMetric ClientTimeStampMetric ResolutionWidthMetric NavigationStartMetric ResolutionHeightMetric CarelessScrollingMetric ScreenOrientationMetric GoogleAnalyticsIdMetric AdobeMarketingCloudIdMetric DurationSinceLastVisitMetric EngagementTimeAggregatorMetric AbtestMetric CartUpdateMetric CartValueMetric ActionMetric ErrorMetric CampaignMetric".split(" ")},
identification:{expirationDays:365,visitTimeSpan:18E5,integrationMessageFormat:"CT2MappingTag_{0}_{1}_{2}_{3}",integrationMethod:function(){return self.ClickTaleEvent}},transport:{preChannel:"pre",mainChannel:"main",terminalChannel:"terminal",url:"https://conductor.clicktale.net/monitor",xhrTimeout:2E3,disableImageChannel:!1},distribution:{maxBackoffInterval:6E4,reliableMessages:{retries:2,waitInterval:1E3},persistence:{storeEnabled:!0,dispatchRetries:3,dispatchEnabled:!0}},onEnd:{useOnBeforeUnload:!1}},
a)}function ra(a,b,c,d,e,f){var g=this;this.o=a;this.w=b;this.g=c;this.i=d;this.oa=e;this.l=f;this.f=this.c=0;this.maxChunkInactivity=C().metrics.maxChunkInactivity;this.modifiedChunkToggle=C().metrics.modifiedChunkToggle;this.a=0;b.forEach(function(a){return a.$(g.b.bind(g)).start()});this.g.bind([6,8],function(){sa(g,function(a){return navigator.onLine?a.start():a.H()})})}
ra.prototype.b=function(){var a=this.i.a();if(!1===a.Ra){var b=Date.now()-this.f;if(this.modifiedChunkToggle&&b<6E4*this.maxChunkInactivity)return}this.f=Date.now();b=this.o.l().value;b>this.c&&(this.c=b,b=this.l,b.a.intr=b.identification.lastModified=y(),D(b,b.a));switch(a.type){case "preinit":this.a=0;break;case "init":this.a=1;break;case "chunk":case "end":this.a++}a.metrics.push({type:5,value:this.a});this.oa.Z(a.metrics,{id:this.a,type:a.type,reliable:a.reliable})};
ra.prototype.dispose=function(a){a||this.b();sa(this,function(a){return a.H()})};function sa(a,b){a.w.forEach(function(a){return b(a)})}function E(a,b){t.call(this,b);this.i=a;this.i.bind(this.c.bind(this))}k(E,t);E.prototype.l=function(){return{type:this.a,value:this.h()}};function F(a,b){E.call(this,a,b);this.g=this.b=0;this.a=26}k(F,E);F.prototype.h=function(){return this.b/(this.g||1)|0||void 0};F.prototype.c=function(a){1E3<=a.K&&(this.g++,this.b+=a.K)};function G(){}
G.prototype.$=function(a){this.g=a;return this};G.prototype.b=function(){this.g()};function ta(){this.b=[];this.f=[];this.a=[]}function ia(a,b){a.f.push(b)}function ua(a,b){a.b.push(b)}ta.prototype.resolve=function(a){H(a,this.a);H(a,this.f)};ta.prototype.reject=function(a){H(a,this.a);H(a,this.b)};function H(a,b){b.forEach(function(b){return b(a)})}
function va(){var a,b;void 0===a&&(a=window);void 0===b&&(b=document);this.a=a;this.f=b;this.b=/ (\w+)(?:\/([\w\.]+))? (?:(\([^\)]+\)) )?/img;this.userAgent=wa(this," "+a.navigator.userAgent+" ")}
function wa(a,b){for(var c=a.a.XMLHttpRequest,d={},e;e=a.b.exec(b);)d[e[1]]={value:e[2],extra:e[3]},a.b.lastIndex--;if(e=/Mobi|Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini|CriOS|bada/i.test(b))try{a.f.createEvent("TouchEvent"),e=!0}catch(u){e=!1}var f=e;e={is:{L:f},ha:{version:0}};var g=e.ha,l=d.Mozilla&&d.Mozilla.extra?d.Mozilla.extra:null;e.supports={sendBeacon:!!a.a.navigator.sendBeacon,bb:c&&"withCredentials"in new XMLHttpRequest,Ja:xa()};if(d.Opera)return g.name="Opera",g.type=
1,(d=/Version\/(\d+)/i.exec(b))&&d[1]&&(g.version=Number(d[1])),e;if(d.Edge)return g.type=0,g.name="Edge",g.version=parseInt(d.Edge.value),e.is.L=f||-1!==b.indexOf("Windows Phone; "),e;if(l&&(c=void 0,c=l.indexOf("MSIE "),-1<c+l.indexOf("; Trident/")&&(c=-1!==c?c:l.indexOf("; rv:"),-1!==c)))return g.name="IE",g.type=7,g.version=parseFloat(l.substr(c+5,3)),e.is.L=f,e;if(d.Firefox&&d.Firefox.value)return g.type=5,g.name="Firefox",g.version=parseFloat(d.Firefox.value),e.is.L=f||l&&-1!==l.indexOf("Android; "),
e;if(c=/Firefox\/(\d+)/i.exec(b))return g.type=5,g.name="Firefox",c[1]&&(g.version=Number(c[1])),e;if(d.Chrome&&d.Chrome.value||d.CriOS&&d.CriOS.value)return g.type=3,g.name="Chrome",g.version=parseFloat(d.Chrome?d.Chrome.value:d.CriOS.value),e.is.L=f||d.CriOS||l&&-1!==l.indexOf("; Android "),e;d.Safari&&(g.name="Safari",l&&-1===l.indexOf("Windows")&&d.Version&&d.Version.value&&(g.type=4,g.version=parseFloat(d.Version.value),e.is.L=f));return e}
function xa(){var a=Function.prototype;if(!a||!a.bind)return!1;a=Date.prototype;if(!(Date.now&&a&&a.toISOString&&a.toJSON))return!1;a=Array.prototype;return!!(a&&a.every&&a.filter&&a.forEach&&a.indexOf&&a.lastIndexOf&&a.map&&a.some&&a.reduce&&a.reduceRight&&Array.isArray)}function ya(a){this.f=a;this.a=[];this.a.push(this.Pa);this.a.push(this.Qa);this.a.push(this.Ka);this.a.push(this.Na);this.a.push(this.Oa)}h=ya.prototype;h.Qa=function(a){return a.direction.T&&350>a.I.B&&650>=a.I.duration&&.5<a.speed};
h.Na=function(a){return a.direction.T&&100>a.I.B&&300>=a.I.duration};h.Oa=function(a){return a.direction.T&&30>a.I.B};h.Ka=function(a){return 1===a.W};h.Pa=function(a){return 0===a.direction.value};function za(a,b,c){var d=this;this.metrics=a;this.config=b;this.reliable=!0;this.b=3;this.f={p:1,2:1,3:1,4:1,7:1,12:1};a.filter(function(a){return a.f});ia(c,function(a){a.reliable&&a.type!=m[1]&&Aa(d)});this.a=Ba(this)}function Ba(a){return I(a,a.metrics.filter(function(a){return a.f}),3,!0)}
function Ca(a){return I(a,a.metrics.filter(function(a){return a.J}),1,!0,!0)}function Da(a){return I(a,a.metrics.filter(function(a){return a.w}),2)}function Ea(a){return I(a,a.metrics.filter(function(a){return a.o}),0)}function I(a,b,c,d,e){void 0===d&&(d=!1);void 0===e&&(e=!1);return function(){var f=Fa(a,b,c,e);a.b=c;d&&Aa(a);return f}}
function Fa(a,b,c,d){var e=b.map(function(a){return a.l(c)});b=b.some(function(a){return a.Y});e=e.filter(function(b){return b.value||a.f[b.type]});return{reliable:d,type:m[c],metrics:e,Ra:b}}function Aa(a){switch(a.b){case 3:a.a=Ca(a);break;case 1:a.a=Da(a);break;case 2:a.a=Ea(a)}}za.prototype.la=function(){return m[this.b]};function Ga(){}function Ha(a){return ea(a).split(",").map(function(a){return a.replace(/'/g,"''").replace(/[\"]/g,"'")}).join("|")}
function Ia(a){a=a.replace(/[{}]/g,"").split("|").map(function(a){a=a.split(":");var c=a[1];a[0]=a[0].replace(/'/g,'"');isNaN(a[1])&&(a[1]=('"'+c.substring(1,c.length-1)+'"').replace("''","'"));return a.join(":")});return JSON.parse("{"+a.join(",")+"}")}function Ja(a,b,c,d){r.call(this,a,b,c,d)}k(Ja,r);function J(a){return{value:a,encoded:decodeURIComponent(a)!==a}}
function Ka(a){return{host:J(a.host),protocol:J(a.protocol.replace(":","")),hash:J(a.hash),search:{value:a.search?"?"+encodeURIComponent(decodeURIComponent(a.search.substring(1))):"",encoded:!0},pathname:J(a.pathname)}}
function K(a,b){r.call(this,!0,!0,!1,!1);this.b=!1;this.c=!0;this.a=7;var c;"string"==typeof a?(c=document.createElement("a"),c.href=a):c=a;c!==b.location&&(c.hash=c.hash||"",c.search=c.search||"",c.href=c.protocol+"//"+c.host+c.pathname+c.search+c.hash);this.href=c.href;this.location=Ka(c)}k(K,Ja);K.prototype.h=function(){return this.c||this.b?(this.c=!1,this.href):this.location};K.prototype.dispose=function(){this.b=!0};function La(){}
La.prototype.a=function(a){var b={};a.forEach(function(a){return b[ba[a.type]]=a.value});return ea(b)};La.prototype.b=function(){return null};function L(){}L.prototype.resolve=function(){};L.prototype.reject=function(){};function Ma(a,b,c){this.f=a;this.app=b;this.b=c}function Na(a,b,c){void 0===c&&(c=0);a.reset(c);a.f.R.resolve(b)}function Oa(a,b,c){void 0===c&&(c=0);a.reset(c);a.app.na()&&a.f.R.reject(b)}function Pa(a,b){var c=b.message.data;return a.b?a.b.a(c):c}
function M(a,b,c,d,e){void 0===e&&(e="POST");Ma.call(this,a,b,c);this.xhrTimeout=d;this.c=e;this.a=new XMLHttpRequest;(a=self.ClickTaleMonitor.Settings.get())&&a.xhrCreatedCallback(this.a)}k(M,Ma);
M.prototype.send=function(a,b){var c=this;try{var d=this.a,e="GET"===this.c;e&&(a+="&"+Pa(this,b));d.open(this.c,a);d.timeout=this.xhrTimeout;d.setRequestHeader("Content-Type","text/plain");this.a.onreadystatechange=function(){4===d.readyState&&(200===d.status?Na(c,b):Oa(c,b))};d.onload=function(){return Na(c,b)};d.onerror=d.ontimeout=d.onabort=function(){return Oa(c,b)};if(e)d.send();else{var f=Pa(this,b);d.send(f)}}catch(g){Oa(this,b),x.error("xhr1",g)}};
M.prototype.reset=function(){var a=this.a;a&&(a.onabort=a.ontimeout=a.onerror=a.onload=a.onreadystatechange=null)};function Qa(a,b,c,d,e,f){this.config=c;this.g=d;this.cookie="ctm";this.f=!1;a:{b=this.config.identification.cookie;a=-2;if(b){if(b.currentDomain){this.b="";break a}if(b.domain){this.b=b.domain;break a}}b=document.location.hostname;-1<b.indexOf(".co.")&&(a=-3);this.b=b.split(".").slice(a).join(".")}Ra(this,f)}
function Ra(a,b){var c=!1,d=Sa(),e=!b&&ClickTaleMonitor&&ClickTaleMonitor.pgv,f=a.config.identification.visitor,g=a.config.identification.visit;void 0!==f&&d&&f!==d.vstr&&(d=null);d&&(c=Ta(a,d,function(){var b=y();d.vst=g?g:d.vst;if(0===d.vst||a.g.Z(d))a.f=!0,d.vst=g||N(),d.lvst=a.c=Math.round((b-d.intr)/6E4);d.intr=b;a.c=d.lvst;d.pgv=e||N();return d}));c||(a.f=!0,D(a,a.a={pgv:e||N(),vst:g||N(),vstr:f||N(),intr:y()}));Ua(a)}
function Sa(){var a,b=0,c=0,d=0,e=!1,f=document.cookie,g=f.split(";");a="ctm=";for(var l=0;l<g.length;l++){var u=g[l];0===u.trim().indexOf(a)&&(-1<u.trim().indexOf("'v':1")?(b=c+u.length,d=c+u.split("=")[0].length+1,e=!0):Va(a.substring(0,a.length-1),"",-1,void 0));c+=u.length+1}if(a=e?f.substring(d,b):null)try{return Ia(a)}catch(bd){}return null}
function Ua(a){a.identification={visit:a.a.vst,visitor:a.a.vstr,N:a.a.pgv,cb:a.a.lvst,lastModified:a.a.intr};x.addToContext({visit:a.a.vst,visitor:a.a.vstr,pageView:a.a.pgv,clientVersion:"1.4.11"})}function Ta(a,b,c){return Wa(b)?(b=c?c(b):b,D(a,b),a.a=b,!0):!1}function Wa(a){var b=["vst","pgv","vstr","intr"];"lsvt"in a&&b.push("lvst");return b.every(function(b){b=a[b];return!isNaN(parseFloat(b))&&isFinite(b)})}function D(a,b){b.v=1;Va(a.cookie,Ha(b),a.config.identification.expirationDays,a.b)}
function Xa(a,b,c,d){var e=this;this.j=b;this.config=c;this.app=d;b=[4];var f=this.dispose.bind(this);c.onEnd.useOnBeforeUnload&&b.push(12);setTimeout(function(){return f(!1,!0)},c.identification.visitTimeSpan);a.bind(b,function(){return e.dispose()})}
Xa.prototype.dispose=function(a,b){var c=this.a;c.a=Ea(c);this.j.dispose(a);if(b){var c=this.j.resolve("IdentificationService"),d=this.config,e=this.app,f=c.identification,g=d.transport.url.replace("/monitor","/visitended"),d=new M({waitInterval:0,R:new L},e,null,d.transport.xhrTimeout),e={message:{data:ea({projectId:e.va(),visitorId:f.visitor,visitId:f.visit})}};d.send(""+g,e);g=Sa();D(c,c.a={pgv:null!==g?g.pgv:N(),vst:0,vstr:null!==g?g.vstr:N(),intr:y()})}this.app.ra()};Xa.prototype.pa=function(){this.dispose(!0)};
function O(a,b,c){r.call(this,!1,!1,!1,!0);this.g=a;this.c=!1;this.ba();a.bind(this.ka(),this.ta());a=this.qa.bind(this);var d={M:{}};Ya(b.a,c.metrics.interestInterval,d)&&!d.M.done&&d.M.ia.push(a)}k(O,r);O.prototype.qa=function(){this.c=!0};function Za(a){var b=a.target;a=q[a.type];return 5===a?!0:7===a&&"href"in b}O.prototype.ba=function(){};function P(a,b,c){O.call(this,a,b,c);this.b=!0;this.a=23}k(P,O);P.prototype.ka=function(){return this.g.i.concat([5])};
P.prototype.ta=function(){var a=this;return function(b){a.c?a.b=!1:Za(b)&&(a.b=!1)}.bind(this)};P.prototype.h=function(){return this.b};function $a(){}$a.prototype.a=function(a){return bb(a)};$a.prototype.b=function(a){return a.split("&").map(function(a){a=a.split("=");var c=a[1],d=Number(c);return{type:Number(a[0]),value:isNaN(d)?"true"===c?!0:"false"===c?!1:decodeURIComponent(c):d}})};
function bb(a){for(var b=[],c=0;c<a.length;c++){var d=a[c];d&&b.push(d.type+"="+encodeURIComponent(d.value))}return b.join("&")}function cb(a,b,c,d){a=new a({waitInterval:0,R:new L},d,null,b.transport.xhrTimeout);c={message:{data:bb([{type:"p",value:c}])}};a.send(b.transport.url+"?t="+m[4],c)}function db(a){this.a=a}k(db,G);function eb(a){this.a=a;this.f=this.b.bind(this)}k(eb,db);eb.prototype.start=function(){this.a.bind([0],this.f)};eb.prototype.H=function(){this.a.aa([0],this.f)};
function fb(){}function N(){var a=window.crypto||window.msCrypto;if(a){var b=new Uint32Array(2);a.getRandomValues(b);for(var a=b[0]&2097151,c=32;0<c--;)a=2*a;b=a-1+b[1];return-1===b?0:b}return Math.floor(Math.random()*ha)}function gb(a,b){t.call(this,b,!1,!0,!0);this.c=a;this.i=/^https?:\/\/((s2?)|(cdn(a|poc|ssl)*))\.clicktale\.net\/.+\.js/i;this.a=11;this.b=0;this.c.bind([0],this.g.bind(this))}k(gb,t);gb.prototype.g=function(a){this.i.test(a.filename)||this.b++};gb.prototype.h=function(){return this.b};
function Q(a,b){t.call(this,b);this.g=a;this.config=b;this.a=28;this.i=this.c=0;this.m=1;this.S=2;this.Da=4;this.touchMouseIgnoreTime=this.config.metrics.touchMouseIgnoreTime;this.b=0;this.g.bind([1],this.da.bind(this));this.g.bind([11],this.ea.bind(this));this.g.bind([9],this.F.bind(this))}k(Q,t);Q.prototype.da=function(){this.b|=this.S};Q.prototype.ea=function(){this.b|=this.Da;this.c=Date.now()};
Q.prototype.F=function(){var a=this,b=this.b&this.m;this.i=Date.now();b||this.c&&!(Math.abs(this.i-this.c)>this.touchMouseIgnoreTime)||(this.c=0,setTimeout(function(){a.c||(a.b|=a.m)},this.touchMouseIgnoreTime))};Q.prototype.h=function(){return this.b};function hb(a){this.config=a}k(hb,n);hb.prototype.a=function(a){return y()-a.intr>=this.config.identification.visitTimeSpan?!0:this.f.a(a)};hb.prototype.b=function(a){this.f=a};function ib(){}ib.prototype.Z=function(a){return this.a.a(a)};
function jb(){}jb.prototype.a=function(){return!1};function kb(a){this.config=a;var b=new p,c=new jb;this.a=new hb(a);this.a.b(b);b.b(c)}k(kb,ib);kb.prototype.Z=function(a){return this.a.a(a)};function lb(){w.call(this);this.b=null;this.a=34;var a=window.ga;a&&"function"===typeof a.getAll&&(a=a.getAll())&&a.length&&"function"===typeof a[0].get&&(this.b=a[0].get("clientId"))}k(lb,w);lb.prototype.h=function(){return this.b};function mb(a,b,c){O.call(this,a,b,c);this.config=c;this.i=!1;this.a=24}
k(mb,O);h=mb.prototype;h.ba=function(){var a=this;O.prototype.ba.call(this);this.b=function(b){!a.c&&Za(b)&&(a.m=Date.now())}.bind(this)};h.qa=function(){O.prototype.qa.call(this);this.g.aa(this.ka(),this.b)};h.ka=function(){return[7,5]};h.ta=function(){return this.b};h.h=function(){return this.i};h.dispose=function(){Date.now()-this.m<this.config.metrics.goalOrientedCloseInterval&&(this.i=!0)};
function nb(a,b){ClickTaleGlobal.persistence.PersistenceDispatcher.call(this,a);this.supportedMessageNames=a;this.oa=b}k(nb,ClickTaleGlobal.persistence.PersistenceDispatcher);nb.prototype.dispatch=function(a,b){this.dispatched=!0;this.oa(a,b)};function ob(a){r.call(this,!1,!0,!1);this.b=a;this.a=31}k(ob,r);ob.prototype.h=function(){return this.b.f};function R(a){t.call(this,a);this.c=!1;this.b=[];this.a=21}k(R,t);R.prototype.h=function(){return this.b.length?this.b:null};
R.prototype.H=function(){this.c=!1};R.prototype.start=function(){this.c=!0};R.prototype.$=function(a){this.g=a;return this};function pb(a){r.call(this,!1,!1,!0,!0);this.g=a;this.c=this.b=0;this.ca=!0;this.a=9;this.g.bind(a.i,this.i.bind(this))}k(pb,r);pb.prototype.i=function(){var a=Date.now();this.c&&(this.b+=Math.min(2E4,a-this.c));this.c=a};pb.prototype.h=function(){return this.b};function qb(a,b,c){this.b=a;this.a=c}
qb.prototype.send=function(a,b){var c=b.message.data,c=this.a?this.a.a(c):c;navigator.sendBeacon(a+"&"+c)?this.b.R.resolve(b):this.b.R.reject(b)};function rb(a){w.call(this);this.b=a;this.a=15}k(rb,w);rb.prototype.h=function(){return this.b.c};function sb(a,b,c){Ma.call(this,a,b,c);this.c=0;this.a={}}k(sb,Ma);sb.prototype.send=function(a,b){var c=this,d=Pa(this,b),e=new Image,f=++this.c;this.a[f]=e;e.onload=function(){return Na(c,b,f)};e.onerror=function(){return Oa(c,b,f)};e.src+=a+"&"+d+"&r="+(new Date).getTime()};
sb.prototype.reset=function(a){delete this.a[a]};function tb(a){r.call(this,!1,!0,!1,!1);this.referrer=a;this.a=8;a&&(a=document.createElement("A"),a.href=this.referrer,this.location=Ka(a))}k(tb,Ja);tb.prototype.h=function(){return this.location||this.referrer};function ub(a){w.call(this);this.timing=a;this.a=10}k(ub,w);ub.prototype.h=function(){return this.timing.domContentLoadedEventEnd-this.timing.navigationStart};
function S(a){this.Y=this.w=this.J=this.o=this.f=!1;this.a=ha;this.navigationStart=a.navigationStart;this.b=this.c=this.a=0}S.prototype.l=function(){return{value:{sum:this.c,max:0,min:this.a,count:this.b},type:this.u()}};function vb(a,b){z.call(this,0,b,[!1,!1,!0,!0]);this.c=Infinity;this.i=!1;this.b={amount:{type:"number",required:!0},action:{values:["other","add","remove"],required:!0},currency:{type:"string",required:!0,C:3},products:{type:"number",required:!1}}}k(vb,z);
vb.prototype.g=function(a,b){var c={amount:[],products:[],currency:void 0};a.forEach(function(a){c.amount.push(wb(a,"amount"));c.products&&c.products.push(wb(a,"products"));c.currency=a.currency});return b?"["+c.products+"]\v"+c.currency+"\v["+c.amount+"]":c};function wb(a,b){var c=a[b];2===a.action&&(c=-1*a[b]);return c}vb.prototype.u=function(){return 62};function xb(){r.call(this,!1,!0,!0,!1);this.a=22;this.ca=!0}k(xb,r);xb.prototype.h=function(){return y()};
function yb(a,b){z.call(this,0,b,[!1,!0,!0,!0]);this.c=Infinity;this.i=!1;this.b={gesture:{values:["other","click"],required:!0},category:{values:"other;cart;banner;menu;carousel;submit;call to action;navigation".split(";"),required:!0},name:{type:"string",required:!1,C:20}}}k(yb,z);yb.prototype.g=function(a,b){return b?zb(a):a};function zb(a){return a.reduce(function(a,c,d){return a+(""+(0!==d?"\v":"")+c.gesture+"\v"+c.category+"\v"+(c.name?c.name:""))},"")}yb.prototype.u=function(){return 63};
function Ab(a){w.call(this);this.a=19;this.userAgent=a.userAgent}k(Ab,w);Ab.prototype.h=function(){return this.userAgent.ha.version};function Bb(a){w.call(this);this.a=18;this.userAgent=a.userAgent}k(Bb,w);Bb.prototype.h=function(){return this.userAgent.ha.name};function Cb(){this.type=3;this.X=[1,2]}function Db(a){S.call(this,a)}k(Db,S);Db.prototype.u=function(){return 101};function Eb(a){r.call(this,!1,!1,!1,!0);this.b=a;this.a=36}k(Eb,r);
Eb.prototype.h=function(a){var b=[],c=Fb(this.b),d;for(d in c)b.push({type:parseInt(d),value:c[d]});return b.length?0==a?b.map(function(a){return a.type+"\v"+a.value}).join("\v"):b:null};function Gb(a){r.call(this,!1,!0,!1,!0);this.app=a;this.a=98}k(Gb,r);Gb.prototype.h=function(){return this.app.ua()};function T(a){r.call(this,!0,!0,!0,!0);this.identification=a.identification}k(T,r);function Hb(a){T.call(this,a);this.a=3}k(Hb,T);Hb.prototype.h=function(){return this.identification.visit};
function U(){r.call(this,!1,!0,!0,!0);this.retries=5}k(U,r);U.prototype.b=function(a,b,c,d){for(var e=document.cookie.split(";"),f=0,g=e.length,l=void 0;f<g;f++)if(l=e[f].trim().match(a))return Ib(l[c],b,d);return null};function Ib(a,b,c){a=a||"";return(b=(decodeURIComponent(a)||a).match(b))?b[c]:null}U.prototype.h=function(){var a=this.g;!a&&this.retries--&&(this.g=a=this.c());return a};function Jb(){U.apply(this,arguments);this.a=33}k(Jb,U);
Jb.prototype.c=function(){return fa(function(){var a=self.s;return(a=a&&a.visitor)&&a.getMarketingCloudVisitorID()})||U.prototype.b.call(this,/AMCV_(.*)AdobeOrg\=(.*)/,/MCMID\|(.*?)\|/,2,1)};function Kb(){w.apply(this,arguments);this.a=30}k(Kb,w);Kb.prototype.h=function(){return self.innerHeight|0};function Lb(){U.apply(this,arguments);this.a=32}k(Lb,U);
Lb.prototype.c=function(){var a=/s_fid\=(.*)/,b=/.+?\|([^\[|]+)/;return fa(function(){var a=self.s,d=a&&a.c_r;return d&&Ib(d("s_vi"),b,1)||a&&a.fid||d&&d("s_fid")})||U.prototype.b.call(this,/s_vi\=(.*)/,b,1,1)||U.prototype.b.call(this,a,a,0,1)};function Mb(a){S.call(this,a)}k(Mb,S);Mb.prototype.u=function(){return 100};
function Nb(a,b,c,d){void 0===c&&(c=document);void 0===d&&(d=window);t.call(this,b);this.g=a;this.c=c;this.F=d;this.a=13;this.m=this.i.bind(this);this.b=0;this.g.bind([2,3],this.m);this.i()}k(Nb,t);Nb.prototype.i=function(){var a=this.c.documentElement,b=this.c.body,a=((this.F.innerHeight||a.clientHeight||b.clientHeight)+(a.scrollTop||b.scrollTop))/(a.scrollHeight||b.scrollHeight)*100,a=Math.abs(Math.round(Math.min(100,a)));this.b=Math.max(a,this.b);100===this.b&&this.g.aa([2,3],this.m)};
Nb.prototype.h=function(){return this.b};function Ob(){w.apply(this,arguments);this.a=17}k(Ob,w);Ob.prototype.h=function(){return screen.height};function V(a,b,c){this.f=a;this.c=(this.c=c)||1E3;this.reset(b)}V.prototype.curr=function(){return Pb(this,!1)};V.prototype.next=function(){return Pb(this,!0)};V.prototype.reset=function(a){this.b=a?a.b:0;this.a=a?a.a:1;this.g=!1};function Pb(a,b){if(a.g)return a.f;var c=(a.b+a.a)*a.c;if(c>a.f)a.g=!0,c=a.f;else if(b){var d=a.b;a.b=a.a;a.a+=d}return c}
function Qb(a,b,c,d){var e=this;this.f=a;this.config=b;this.app=c;this.A=d;this.c=new V(this.config.metrics.maxFetchInterval);ia(this.A,function(){return e.deThrottle()});ua(this.A,function(){return e.throttleUp()})}k(Qb,G);h=Qb.prototype;h.start=function(){var a=this;Rb(this,!0);Sb(this.f,function(){return a.b()})};h.deThrottle=function(){this.a=null;Tb(this,!0)};h.throttleUp=function(){this.a||(this.a=new V(this.config.distribution.maxBackoffInterval,this.c));Tb(this)};
function Tb(a,b){var c=(a.a||a.c).next();a.H();a.app.na()&&(a.l=setTimeout(function(){a.b();b&&Tb(a,!0)},c))}h.H=function(){clearTimeout(this.l)};h.dispose=function(){this.H();Rb(this)};function Rb(a,b){var c=a.f;(b?c.bind:c.aa).call(c,[6],function(){return a.deThrottle()})}
function Ub(a,b,c){this.userAgent=b;this.i=c;this.W=this.c=0;this.f=[];this.g=[];this.o=[];this.f.push(this.ya.bind(this));this.f.push(this.Ha.bind(this));this.g.push(this.Ma.bind(this));this.g.push(this.Za.bind(this));this.J=new ya(this.Ea.bind(this));a.bind([2],this.Ua.bind(this));a.bind([3],this.Ta.bind(this))}h=Ub.prototype;h.bind=function(a){this.o.push(a)};
h.Ua=function(){var a=Vb(this);clearTimeout(this.l);this.a&&(a.K=a.time-this.a.time,a.B=a.D-this.a.D,a.direction=a.B/(Math.abs(a.B)||1));var b;a:{b=0;for(var c=this.g;b<c.length;b++)if((0,c[b])(a)){b=!1;break a}b=!0}if(b){a:{b=0;for(c=this.f;b<c.length;b++)if((0,c[b])(a)){b=!0;break a}b=!1}b&&(Wb(this),a.direction=0,a.K=a.B=0);this.b||(this.b=a);this.a=a;this.W++;Xb(this)}};h.Ta=function(){this.c=Date.now()};h.Ea=function(a){this.o.forEach(function(b){return b(a)})};
h.Ma=function(a){return 70>=a.time-this.c?(this.c=0,!0):!1};h.Za=function(a){return this.userAgent.is.L&&this.a?20>a.time-this.a.time:!1};h.Ha=function(a){return this.a?0===this.a.direction?0>(this.a.D-this.b.D)*a.direction:0==a.direction+this.a.direction:!1};h.ya=function(a){return this.a&&1E3<=a.time-this.a.time?!0:!1};function Xb(a){a.l=setTimeout(function(){clearTimeout(a.l);a.ya(Vb(a))&&Wb(a)},1E3)}function Vb(a){return{K:0,B:0,time:Date.now(),D:a.i.pageYOffset,direction:0}}
function Wb(a){if(a.b){var b=a.J,c=a.b,d=a.a||a.b,e=d.D-c.D,c={xa:0,K:0,speed:0,W:a.W,start:{time:c.time,D:c.D},end:{time:d.time,D:d.D},I:{B:Math.abs(e),duration:d.time-c.time},direction:{value:0,T:!1}};c.speed=c.I.B/c.I.duration||1;c.direction.value=e/(c.I.B||1);b.b&&(c.xa=b.b.xa+1,c.K=c.start.time-b.b.end.time,c.direction.T=0!==c.direction.value&&c.direction.value!==b.b.direction.value);a:{e=0;for(d=b.a;e<d.length;e++)if((0,d[e])(c)){e=!1;break a}e=!0}e&&(b.b=c,b.f(c));a.a=a.b=null;a.W=0}}
h.dispose=function(){!this.w&&(this.w=!0)&&Wb(this)};function Yb(){}function Va(a,b,c,d){var e="";c&&(e=new Date,e.setTime(e.getTime()+864E5*c),e="; expires="+e.toUTCString());document.cookie=a+"="+b+e+"; path=/;"+(d?" domain="+d+";":"")}function Zb(a,b){for(var c=1;c<arguments.length;c++);var d=Array.prototype.slice.call(arguments,1);return a.replace(/\{(\d+)\}/g,function(a,b){return d[b]})}function $b(a){t.call(this,a);this.a=this.u()}k($b,t);$b.prototype.H=function(){};$b.prototype.start=function(){};
$b.prototype.$=function(){return this};function ac(a,b,c){ClickTaleGlobal.persistence.PersistenceClient.call(this,a,b,c)}k(ac,ClickTaleGlobal.persistence.PersistenceClient);ac.prototype.sendMessages=function(){ClickTaleGlobal.persistence.PersistenceClient.prototype.sendMessages.call(this)};function bc(a){this.o=this.f=!1;this.J=this.w=!0;this.Y=!1;this.c=0;this.b=!1;this.a=0;this.navigationStart=a.navigationStart}function cc(a){var b=Date.now();a.b&&(a.a+=b-a.c,a.c=b)}
bc.prototype.l=function(){cc(this);return{type:this.u(),value:Date.now()-this.navigationStart-this.a}};function dc(a,b){this.a={};var c=a.transport,d={};d[m[3]]=c.preChannel;d[m[1]]=d[m[2]]=c.mainChannel;d[m[0]]=c.terminalChannel;for(var e in d)this.a[e]=ec(b,""+d[e])}function fc(a,b){z.call(this,0,b,[!1,!0,!0,!1]);this.c=1;this.b={name:{type:"string",required:!0,C:20},content:{type:"string",required:!1,C:20},marketingChannel:{type:"string",required:!1,C:20}}}k(fc,z);fc.prototype.g=function(a){return a[0]};
fc.prototype.u=function(){return 64};function W(){}W.prototype.add=function(a,b){this[a.toString()]=b};W.prototype.remove=function(a){delete this[a.toString()]};function Ya(a,b,c){return(a=a[b.toString()])?(c.M=a,!0):!1}W.prototype.values=function(){var a=this;return Object.keys(this).map(function(b){return a[b]})};
function gc(a,b){var c=this;void 0===b&&(b=[]);r.call(this,!1,b.some(function(a){return-1<a.X.indexOf(1)}),!0,b.some(function(a){return-1<a.X.indexOf(0)}));this.g=b;this.b={};this.c={};this.a=this.u();this.maxTagsOnEnd=a.metrics.maxTagsOnEnd;this.i=a.metrics.maxPageTagLength;this.F=a.metrics.pageTagRedundancy;this.m=a.metrics.maxPageTagsPerPage;b.forEach(function(a){c.c[a.type]=[]})}k(gc,r);function Fb(a){var b={},c;for(c in a.c){var d=a.c[c].length;d&&(b[c]=d)}return b}
function hc(a,b,c,d){if("number"===typeof b&&"number"===typeof c&&"string"===typeof d){var e=a.g.filter(function(a){return a.type==c})[0];e&&ic(a,b,c,d,e)}}h=gc.prototype;h.H=function(){};h.start=function(){};h.$=function(){return this};
h.h=function(a){var b=this,c=Object.keys(this.b).map(function(a){return b.b[a]}).filter(function(b){return-1<b.La.X.indexOf(a)&&0<b.Ya--}).map(function(a){return a.tag});return c.length?0==a?(c.splice(this.maxTagsOnEnd),c.map(function(a){return a.id+"\v"+a.type+"\v"+a.value}).join("\v")):c:null};function ic(a,b,c,d,e){var f=d.slice(0,a.i);d=[b,c,f].join("|");a.b[d]||(Object.keys(a.b).length>=a.m?(a=a.c[c],0>a.indexOf(d)&&a.push(d)):a.b[d]=new jc(e,{id:b,type:c,value:f},a.F))}h.u=function(){return 35};
function jc(a,b,c){this.La=a;this.tag=b;this.Ya=c}function kc(a){T.call(this,a);this.a=2;this.o=this.f=!1}k(kc,T);kc.prototype.h=function(){return this.identification.visitor};var lc=/function ([^\(]+)/;function mc(a,b){var c;if(!(c=b)){var d;if("string"===typeof a)d=a;else{if(!((c=a.name)||(c=a.toString().match(lc),c=c&&0<c.length&&c[1]))){c=[];var e=a.prototype;for(d in e)c.push(d);c=c.join("")}d=c}c=d}this.a=c}mc.prototype.toString=function(){return this.a};
function nc(){w.apply(this,arguments);this.a=6}k(nc,w);nc.prototype.h=function(){return"1.4.11"};function oc(a){this.U=a}k(oc,pc);function qc(a,b){1!==a.P&&(a.V=b);0===a.G&&b.dispose&&a.j.a.push(b);a.ma&&a.ma(a.j,b)}function rc(a){var b=new oc(a.U);b.G=a.G;b.P=a.P;b.V=a.V;b.j=a.j;b.ma=a.ma;return b}function X(){this.a=[];this.b=new W;var a=rc({V:this,U:function(a){return a},j:this,G:1,P:0});this.b.add(new mc(X),a)}X.prototype.dispose=function(a){for(;0<this.a.length;)this.a.shift().dispose(a)};
function Y(a,b,c){return sc(a,b,null,c)}function tc(a,b,c){a=sc(a,Object.getPrototypeOf(c).constructor,b,null);a.P=0;a.G=1;qc(a,c)}function sc(a,b,c,d){b=new mc(b,c);d=rc({j:a,U:d,P:0,G:0});a.b.add(b,d);return d}X.prototype.resolve=function(a,b,c,d,e){return this.f.apply(this,[a,null,b,c,d,e])};X.prototype.f=function(a,b,c,d,e,f){var g;g=Array.prototype.slice.call(arguments,2);var l,u=uc(this,a,b);u?(l=u.V,l||(g=g||[],g.splice(0,0,u.j),l=u.U.apply(null,g),qc(u,l)),g=l):g=null;return g};
function ec(a,b){var c,d=uc(a,b,null);return d?function(a,b,g,l){a=[d.j,a,b,g,l];c=d.V;c||(c=d.U.apply(null,a),qc(d,c));return c}:function(){return null}}function uc(a,b,c){var d;b=new mc(b,c);c={};Ya(a.b,b,c)&&(d=c.M);return d}function pc(){}function vc(a){a.P=1;return a}function wc(a){w.call(this);this.userAgent=a;this.b=0;this.a=27}k(wc,w);wc.prototype.h=function(){this.userAgent.is.L&&(this.b=self.innerHeight>=self.innerWidth?1:2);return this.b};
function xc(a){r.call(this,!1,!0,!0,!1);this.b=a;this.a=1}k(xc,r);xc.prototype.h=function(){return this.b};function yc(a,b){E.call(this,a,b);this.b=0;this.a=25}k(yc,E);yc.prototype.h=function(){return this.b};yc.prototype.c=function(a){a.direction.T&&1E3>a.K&&this.b++};function zc(a){var b=this;this.a=new W;a.forEach(function(a){return Ac(b,a)})}function Ac(a,b){a.a.add(b,{ia:[],done:!1});setTimeout(function(){return a.done(b)},b)}
zc.prototype.done=function(a){this.a[a.toString()]&&(a=this.a[a],a.ia.forEach(function(a){return a()}),a.ia=null,a.done=!0)};function Bc(){this.c=!1;this.o=[];this.l=this.Sa.bind(this);this.b=this.Xa.bind(this);this.a=new W;this.i=[10,7,1,2,3,11];this.g=[2,3,6,8,12,4];this.f=[9,10,7,1,14,5,11];Cc(this)}
function Cc(a){a.f.concat(a.g).concat([13]).forEach(function(b){a.a[b]=[]});Dc(a);(a.c=/complete|interactive/.test(document.readyState))||document.addEventListener("DOMContentLoaded",function(){return setTimeout(a.l,0)},!1)}h=Bc.prototype;h.bind=function(a,b){Ec(this,a,b)};h.aa=function(a,b){var c=this;a.forEach(function(a){if(c.a){a=c.a[a];var e=a.indexOf(b);-1<e&&a.splice(e,1)}})};
function Ec(a,b,c){var d;void 0===d&&(d=!1);var e=d?function(a){return a.splice(0,0,c)}:function(a){return a.push(c)};b.forEach(function(b){return e(a.a[b])})}h.Xa=function(a){this.a[q[a.type]].forEach(function(b){return b(a)})};h.dispose=function(){this.a=null;Fc(this)};function Sb(a,b){a.c?b():a.o.push(b)}h.Sa=function(a){this.c=!0;this.o.forEach(function(b){return b(a)});document.removeEventListener("DOMContentLoaded",this.l,!1)};
function Dc(a){function b(a){return a.addEventListener}Gc(b,window,a.g,a.b);Gc(b,document,a.f,a.b);a.a[0]=[];var c=a.w=window.onerror;window.onerror=function(b,e,f,g,l){c&&c(b,e,f,g,l);a.b({filename:e,type:q[0]});x.jsError("jserr1",b,f,g,e)}}function Fc(a){function b(a){return a.removeEventListener}Gc(b,window,a.g,a.b);Gc(b,document,a.f,a.b);window.onerror=a.w}function Gc(a,b,c,d){c.forEach(function(c){c=q[c];a(b).apply(b,[c,d,!1])})}
function Hc(a,b){z.call(this,0,b,[!1,!0,!0,!1]);this.c=1;this.b={amount:{type:"number",required:!0},currency:{type:"string",required:!0,C:3},products:{type:"number",required:!1}}}k(Hc,z);Hc.prototype.g=function(a){return a[0]};Hc.prototype.u=function(){return 61};
function Ic(a,b,c,d,e,f,g,l){var u=this;this.o=a;this.app=c;this.config=d;this.l=e;this.i=g;this.A=l;this.f=!1;this.b=new W;this.g=new $a;this.J=d.transport.url;a=d.distribution;this.w={R:{reject:this.Wa.bind(this),resolve:this.Ca.bind(this)},waitInterval:a.reliableMessages.waitInterval};this.identification=b.identification;this.l.bind([6,8],function(){return u.wa});this.c=new nb([m[0]],this.Ia.bind(this));this.a=new ac(f,this.c,d.identification.visitTimeSpan);(this.storeEnabled=a.persistence.storeEnabled)&&
this.a.startSession(this.identification.N);this.wa()}h=Ic.prototype;
h.Z=function(a,b){var c;c={data:a};var d={};if(b.reliable&&Ya(this.b,b.id,d)){if(c=d.M,0>--c.retries)return this.app.pa()}else c={message:c,metrics:b,retries:this.config.distribution.reliableMessages.retries,O:{name:b.type,enabled:b.type===m[0]}},this.b.add(b.id,c);d=this.J+"?t="+c.metrics.type+"&p="+this.o+"&2="+this.identification.visitor+"&v=1.4.11";Jc(this,c,d);Kc(this,c,d)&&this.storeEnabled&&(c.metrics.type===m[0]?this.a.stopSession(this.identification.N):this.a.extendSession(this.identification.N,
this.config.identification.visitTimeSpan))};function Kc(a,b,c){var d=a.i.a[b.metrics.type](a.w);return a.f?("end"===b.metrics.type&&x.info("mntrend1","sending end message"),d.send(c,b),!0):!1}
h.Ia=function(a,b){var c;c={};var d=a.message.data,e=d.data;"string"===typeof e&&(d.data=this.g.b(e));Ya(this.b,d.id,c)?c=c.M:(c={message:d,metrics:{id:0,type:a.message.name,reliable:!1},retries:0,O:{A:b,locator:a.locator,result:a,retries:this.config.distribution.persistence.dispatchRetries}},this.b.add(d.id,c));Kc(this,c,a.message.url)||b.reject(a)};
function Jc(a,b,c){if(b.O.enabled&&!b.O.locator&&a.storeEnabled){var d=a.g.a(b.message.data);b.O.locator=a.a.storeMessage({url:c,data:{id:Date.now(),data:d},name:b.metrics.type,sid:a.identification.N},function(){},!1,!1)}}h.Ca=function(a){var b=a.O;this.a.deThrottle();b.A&&b.A.resolve(b.result);b.locator&&this.a.removeMessage(b.locator);a.metrics&&this.A.resolve(a.metrics)};h.Wa=function(a){var b=a.O;this.a.throttleUp();b.A&&(0<--b.retries?b.A.defer(b.result):b.A.reject(b.result));a.metrics&&this.A.reject(a.metrics)};
h.wa=function(){(this.c.isAvailable=(this.f=navigator.onLine)&&this.config.distribution.persistence.dispatchEnabled)&&this.a.sendMessages()};function Lc(){this.type=4;this.X=[2,0]}function Mc(a,b){bc.call(this,b);this.g=a;this.o=!0;this.g.bind([14],this.i.bind(this))}k(Mc,bc);Mc.prototype.u=function(){return 12};Mc.prototype.i=function(){document.hidden?(this.b=!0,this.c=Date.now()):(cc(this),this.b=!1)};function Nc(a){T.call(this,a);this.a=4}k(Nc,T);Nc.prototype.h=function(){return this.identification.N};
function Oc(a,b,c,d){M.call(this,a,b,c,d,"GET")}k(Oc,M);function Pc(){w.apply(this,arguments);this.a=29}k(Pc,w);Pc.prototype.h=function(){return self.innerWidth|0};function Qc(){w.apply(this,arguments);this.a=16}k(Qc,w);Qc.prototype.h=function(){return screen.width};function Rc(a,b){z.call(this,0,b,[!1,!0,!0,!1]);this.c=Infinity;this.b={vendor:{type:"string",required:!1,C:20},experience:{type:"string",required:!0,C:20}}}k(Rc,z);Rc.prototype.u=function(){return 60};Rc.prototype.g=function(a){return a};
function Z(a,b,c,d){var e=this;this.b=a;this.a=!1;Sc(this,b,c,d);var f=!!(b&&b.constructor.prototype===Object.prototype&&b.location||c);Tc(this,function(){Uc(e,f)&&e.start(f)})}var Vc;function Wc(a,b,c){return{location:b||self.location,referrer:c||document.referrer,onStartCallback:a}}function Sc(a,b,c,d){var e=!!c&&c.constructor.prototype===Object.prototype;a.f=b&&b.constructor.prototype===Object.prototype?Wc(b.onStartCallback,b.location,b.referrer):Wc(b,c,d);e&&(B=qa(c))}h=Z.prototype;
h.ua=function(){return Vc||(Vc=y())};h.va=function(){return this.b};function Tc(a,b){a.a||"file:"===location.protocol||b()}
h.start=function(a){var b=this,c=self.ClickTaleGlobal;c&&Xc("onstarting");var d=this.j,e=d.resolve("Disposer");this.a=!0;d.resolve("EventListenerHub");d.resolve("MetricsReader");d.resolve("DistributionService");e.a=d.resolve("MetricAggregator");if(this.f.onStartCallback)this.f.onStartCallback(this);c&&(c=function(){var a=C(),c=a.identification.integrationMethod(),a=a.identification.integrationMessageFormat,e=d.resolve("IdentificationService").identification,a=Zb(a,b.b,e.visitor,e.visit,e.N);c(a)},
ClickTaleGlobal.scripts.integration.onReady(c),a&&c(),Xc("onstarted"))};function Xc(a){var b=ClickTaleGlobal.diagnostics;a=(b=b&&b.monitor)&&b[a];"function"==typeof a&&a()}
function Uc(a,b){var c=C(),d=new va,e=d.userAgent.supports.sendBeacon?qb:c.transport.disableImageChannel?Oc:sb;if(d.userAgent.supports.Ja){var f=new X;a.j=f;a.g=new R(c);a.c=new gc(c,[new Cb,new Lc]);var g=function(){return f.resolve("EventListenerHub")};Yc(a,c,g,d,b);tc(f,null,d);Zc(a,e,c);Y(f,"ChannelFactory",function(){return new dc(c,f)});Y(f,"IdGenerator",function(){return new fb});Y(f,"MetricsPromise",function(){return new ta});Y(f,"CookiesService",function(){return new Yb});Y(f,"CookieSerializer",
function(){return new Ga});Y(f,"VisitService",function(){return new kb(c)});tc(f,"EventIdsMetric",a.g);tc(f,"TagsMetric",a.c);Y(f,"EventListenerHub",function(){return new Bc});Y(f,"NavigationStartTimerEventHub",function(){return new zc([c.metrics.interestInterval])});Y(f,"AttentionSplitMetric",function(a){return new F(a.resolve("ScrollyBlocksProvider"),c)});Y(f,"CarelessScrollingMetric",function(a){return new yc(a.resolve("ScrollyBlocksProvider"),c)});Y(f,"ScrollyBlocksProvider",function(){return new Ub(g(),
d.userAgent,self)});Y(f,"Disposer",function(b){return new Xa(g(),b,c,a)}).G=1;Y(f,"PeriodicalNotifierRule",function(b){return new Qb(g(),c,a,b.resolve("MetricsPromise"))});Y(f,"IdentificationService",function(a){return new Qa(a.resolve("IdGenerator"),a.resolve("CookiesService"),c,a.resolve("VisitService"),a.resolve("CookieSerializer"),b)});Y(f,"LocalStorageProvider",function(){return new ClickTaleGlobal.persistence.LocalStorageProvider});Y(f,"WindowNameProvider",function(){return new ClickTaleGlobal.persistence.WindowNameProvider});
Y(f,"PersistenceManager",function(a){return new ClickTaleGlobal.persistence.PersistenceManager([a.resolve("LocalStorageProvider"),a.resolve("WindowNameProvider")],new V(c.distribution.maxBackoffInterval))});Y(f,"DistributionService",function(b){return new Ic(a.b,b.resolve("IdentificationService"),a,c,g(),b.resolve("PersistenceManager"),b.resolve("ChannelFactory"),b.resolve("MetricsPromise"))});Y(f,"MetricAggregator",function(a){var b=f.resolve("MetricsPromise"),d=c.metrics.providers.map(function(b){return a.resolve(b)}).concat([a.resolve("VersionMetric"),
a.resolve("LocationMetric"),a.resolve("ProjectIdMetric"),a.resolve("DocumentReferrerMetric"),a.resolve("VisitIdentificationMetric"),a.resolve("DOMContentLoadedTimeMetric"),a.resolve("VisitorIdentificationMetric"),a.resolve("PageViewIdentificationMetric")]);return new za(d,c,b)});Y(f,"MetricsReader",function(a){return new ra(a.resolve("EngagementTimeAggregatorMetric"),[a.resolve("EventIdsMetric"),a.resolve("TagsMetric"),a.resolve("PeriodicalNotifierRule")],g(),a.resolve("MetricAggregator"),a.resolve("DistributionService"),
a.resolve("IdentificationService"))});return!0}cb(e,c,a.b,a);return!1}
function Yc(a,b,c,d,e){function f(){return a.j.resolve("NavigationStartTimerEventHub")}function g(){return a.j.resolve("IdentificationService")}var l=$c(e);[["VersionMetric",function(){return new nc}],["AppLoadTimeMetric",function(){return new Gb(a)}],["ViewPortWidthMetric",function(){return new Pc}],["AdobeLegacyIdMetric",function(){return new Lb}],["ViewPortHeightMetric",function(){return new Kb}],["BrowserMetric",function(){return new Bb(d)}],["ResolutionWidthMetric",function(){return new Qc}],
["ClientTimeStampMetric",function(){return new xb}],["ProjectIdMetric",function(){return new xc(a.b)}],["ResolutionHeightMetric",function(){return new Ob}],["GoogleAnalyticsIdMetric",function(){return new lb}],["LocationMetric",function(){return new K(a.f.location,self)}],["NavigationStartMetric",function(){return new ca(l)}],["AdobeMarketingCloudIdMetric",function(){return new Jb}],["BrowserVersionMetric",function(){return new Ab(d)}],["DocumentReferrerMetric",function(){return new tb(a.f.referrer)}],
["DOMContentLoadedTimeMetric",function(){return new ub(l)}],["ScreenOrientationMetric",function(){return new wc(d.userAgent)}],["ScrollReachMetric",function(){return new Nb(c(),b)}],["JSErrorCountMetric",function(){return new gb(c(),b)}],["NumberOfClicksMetric",function(){return new v(c(),b)}],["TimeOnPageMetric",function(){return new Mc(c(),l)}],["FirstPageviewMetric",function(){return new ob(g())}],["InputMethodMetric",function(){return new Q(c(),b)}],["VisitIdentificationMetric",function(){return new Hb(g())}],
["VisitorIdentificationMetric",function(){return new kc(g())}],["DurationSinceLastVisitMetric",function(){return new rb(g())}],["PageViewIdentificationMetric",function(){return new Nc(g())}],["EngagementTimeAggregatorMetric",function(){return new pb(c())}],["GoalOrientedMetric",function(){return new mb(c(),f(),b)}],["LackOfInterestMetric",function(){return new P(c(),f(),b)}],["DiscardedTagsMetric",function(){return new Eb(a.c)}],["AbtestMetric",function(a){return new Rc(0,a.resolve("MetricsPromise"))}],
["CartValueMetric",function(a){return new Hc(0,a.resolve("MetricsPromise"))}],["CartUpdateMetric",function(a){return new vb(0,a.resolve("MetricsPromise"))}],["ActionMetric",function(a){return new yb(0,a.resolve("MetricsPromise"))}],["ErrorMetric",function(a){return new A(0,a.resolve("MetricsPromise"))}],["CampaignMetric",function(a){return new fc(0,a.resolve("MetricsPromise"))}]].forEach(function(b){return sc(a.j,b[0],null,b[1])})}
function $c(a){var b=(new Date).getTime();return self.performance&&!a&&(a=performance.timing,!isNaN(a.navigationStart)&&18E5>b-a.navigationStart)?a:{domContentLoadedEventEnd:b,navigationStart:Z.a||b}}h.pa=function(){this.dispose(!0)};h.Ba=function(){this.dispose(!1,!0)};h.dispose=function(a,b,c){this.a&&(this.j.resolve("Disposer").dispose(a,b),c||(B=null),delete Z.a)};h.$a=function(a,b){this.dispose(!1,!1,!0);ClickTaleMonitor.Settings.onReady(a,b)};h.ra=function(){this.a&&(this.a=!1,this.l&&this.l())};
h.Va=function(a){this.l=a};h.na=function(){return this.a};function Zc(a,b,c){var d=new $a,e=c.transport;Y(a.j,e.terminalChannel,function(c,g){return new b(g,a,d,e.xhrTimeout)}).G=1;vc(Y(a.j,e.mainChannel,function(b,c){return new M(c,a,new La,e.xhrTimeout)})).G=1;vc(Y(a.j,e.preChannel,function(c,g){return new b(g,a,d,e.xhrTimeout)})).G=1}h.za=function(a){var b=this.g;-1===b.b.indexOf(a)&&(b.b.push(a),b.c&&b.g())};h.fa=function(a,b,c){hc(this.c,a,b,c)};h.Aa=function(a,b,c){this.fa(a,b,c)};
h.Fa=function(a,b,c){this.fa(a,b,c)};h.Ga=function(a){var b="object"===typeof a&&null!==a&&a.event?a.event:void 0;(b=b?this.j.resolve(da(b)+"Metric"):void 0)?b.add(a):x.error("unknown metric","dataEvents")};h.la=function(){return this.j?this.j.resolve("MetricAggregator").la():""};Z.a=self.a||(new Date).getTime();Z.prototype.stop=Z.prototype.ra;Z.prototype.onStop=Z.prototype.Va;Z.prototype.ctData=Z.prototype.Ga;Z.prototype.addTag=Z.prototype.Aa;Z.prototype.dispose=Z.prototype.dispose;
Z.prototype.restart=Z.prototype.$a;Z.prototype.endVisit=Z.prototype.Ba;Z.prototype.getState=Z.prototype.la;Z.prototype.shutdown=Z.prototype.pa;Z.prototype.addEvent=Z.prototype.za;Z.prototype.addPageTag=Z.prototype.Fa;Z.prototype.addTagIntro=Z.prototype.fa;Z.prototype.getLoadTime=Z.prototype.ua;Z.prototype.isMonitoring=Z.prototype.na;Z.prototype.getProjectId=Z.prototype.va;
var ad="object"===typeof module&&"object"===typeof module.exports,ClickTaleMonitor=(ad?module.exports.ClickTaleMonitor:self.ClickTaleMonitor)||{};ClickTaleMonitor.App=Z;ad?module.exports=ClickTaleMonitor:self.ClickTaleMonitor=ClickTaleMonitor;ClickTaleMonitor.version="1.4.11";if (self.ClickTaleMonitor && self.ClickTaleMonitor.Settings) { self.ClickTaleMonitor.Settings.onReady(); }}.call({});
